apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: cilium
      version: '1.13.4'
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
      listenAddress: ':4244'
      relay:
        enabled: true
      ui:
        enabled: true
    ipv6:
      enabled: false
    operator:
      replicas: 1
    securityContext:
      privileged: true