---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-base
  namespace: flux-system
spec:
  path: ./clusters/flux/system/monitoring/grafana/base
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true
  dependsOn:
  - name: traefik-base

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-dashboards
  namespace: flux-system
spec:
  path: ./clusters/flux/system/monitoring/grafana/dashboards
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: grafana-base