---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    name: grafana

---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus
  labels:
    name: kube-prometheus
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged