apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: intel-gpu
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: intel-gpu
  policy:
    semver:
      range: ">=0.25.1"