apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
- repository.yaml
- release.yaml
- default-headers.yaml
- cert.yaml
- ingress.yaml
- tls_options.yaml
- secrets.yaml