apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 24h
  chart:
    spec:
      chart: grafana
      version: '>=6.51.5'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 24h
  values:
    service:
      portName: grafana
      port: 3000
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            isDefault: true
            url: http://kube-prometheus-kube-prome-prometheus.kube-prometheus.svc.cluster.local:9090
            access: proxy
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 300Mi
    admin:
      existingSecret: grafana-secret
      userKey: gf_security_admin_user
      passwordKey: gf_security_admin_password
    sidecar:
      dashboards:
        enabled: true
        labelValue: ""
        searchNamespace: ALL
      datasources:
        enabled: true
        labelValue: ""
        searchNamespace: ALL
    plugins:
      - grafana-piechart-panel
    serviceMonitor:
      enabled: true
    rbac:
      pspEnabled: false