---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adminer-cert
  namespace: adminer
spec:
  secretName: adminer-cert-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "adminer.yourdomain.com"
  dnsNames:
  - "adminer.yourdomain.com"